#!/bin/bash

#
# This file is part of videokit-kde.
# Copyright (C) 2025 Tom Brown
#
# videokit-kde is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# videokit-kde is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


# source utility package

[[ -n "${__KLI_AUR_LIB_SH__}" ]] && return ; readonly __KLI_AUR_LIB_SH__=1


# configuration

aur::projectDir() {

    local PROJECT_DIR="$( kli::getProjectDir )/AUR/$( kli::detectProject )"

    echo "$PROJECT_DIR"

}


aur::createDir() {

    local PROJECT_DIR=$( aur::projectDir )
    if [[ ! -e "$PROJECT_DIR" ]]; then
        app::message "info echo log" "creating $PROJECT_DIR directory"
        mkdir -p "$PROJECT_DIR"
    fi
}


aur::createRepo() {

    if [[ "$KLI_REPO_AUR" == true ]]; then

        app::message "info echo log" "repository $KLI_PROJECT AUR init in directory $PWD"
        git init --initial-branch=main

        if [[ $? ]]; then
            makepkg --printsrcinfo > .SRCINFO
            git add .SRCINFO PKGBUILD LICENSE
        fi

        if [[ $? ]]; then
            app::message "info echo log" "git initial commit"
            git commit -m "initial commit"
        fi

        if [[ $? ]]; then
            app::message "info echo log" "git create remote repo"
            gh repo create $PROJECT --public --source=. --remote=origin --push
            #gh repo create mypackage --public --source=. --remote=origin --push
        fi

    else

        app::message "info echo" "no AUR repo for this project"

    fi
}

